on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        host:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm64
            arch: aarch64
    runs-on: ${{ matrix.host.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          # docker compose run --build --rm builder -c ./build.sh
          mkdir -p output && echo "testing" > output/toolset.tar.gz
          mv output/toolset.tar.gz output/toolset-${{ matrix.host.arch }}.tar.gz
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolset-${{ matrix.host.arch }}
          path: output/toolset-${{ matrix.host.arch }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          pattern: toolset-*
          path: output
      - name: Create and publish release
        id: publish_release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"
          gh release upload "$TAG" output/**/*.tar.gz
