on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: docker compose run --build --rm builder -c ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: output/toolset.tar.gz
